// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6dUKMJLnt5zePSGCZcUJIhOFU09TD5y0',
    appId: '1:97202834244:web:6dd1a43a9edb78496a6511',
    messagingSenderId: '97202834244',
    projectId: 'noticias-41f0a',
    authDomain: 'noticias-41f0a.firebaseapp.com',
    storageBucket: 'noticias-41f0a.firebasestorage.app',
    measurementId: 'G-MWXVT3HJNJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwLnLO6dKemSp6tPEoivFJEHxnAPSL_GM',
    appId: '1:97202834244:android:10e98b37d3d8934e6a6511',
    messagingSenderId: '97202834244',
    projectId: 'noticias-41f0a',
    storageBucket: 'noticias-41f0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi6FiHpg33fe8CH719eeqbZf2phCv9KHU',
    appId: '1:97202834244:ios:9981e4fbf9b028096a6511',
    messagingSenderId: '97202834244',
    projectId: 'noticias-41f0a',
    storageBucket: 'noticias-41f0a.firebasestorage.app',
    iosBundleId: 'com.example.appNoticias',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi6FiHpg33fe8CH719eeqbZf2phCv9KHU',
    appId: '1:97202834244:ios:9981e4fbf9b028096a6511',
    messagingSenderId: '97202834244',
    projectId: 'noticias-41f0a',
    storageBucket: 'noticias-41f0a.firebasestorage.app',
    iosBundleId: 'com.example.appNoticias',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6dUKMJLnt5zePSGCZcUJIhOFU09TD5y0',
    appId: '1:97202834244:web:b4ff891dda7bcaba6a6511',
    messagingSenderId: '97202834244',
    projectId: 'noticias-41f0a',
    authDomain: 'noticias-41f0a.firebaseapp.com',
    storageBucket: 'noticias-41f0a.firebasestorage.app',
    measurementId: 'G-7E29ZH41BW',
  );
}
